### ISSUE TITLE
ETA on jailbreak

### ISSUE THREAD

**Issue by jaybo626** [ModernPwner/cicuta_virosa#19]
I'm on iOS 14.4.1 on iPhone 12 Pro Max I would love to be a tester if possible thank you

**Comment by coredoesdev** [comment]
This is not a jailbreak. This is a kernel LPE, or local privlage escalation. This is the thing that jailbreak developers can use to make jailbreaks.

**Comment by jaydumisuni** [comment]
Thanks

**Comment by jaydumisuni** [comment]
Thanks for the updates looks promising 🙌🏾
