### ISSUE TITLE
iOS 14.5.1 (maybe it's same as 14.5)

### ISSUE THREAD

**Issue by joeyoropesa-dev** [ModernPwner/cicuta_virosa#23]
Have you discovered more secure vulnerabilities for iOS 14.5.1 that you could publish soon in 2021/2022

**Comment by SmartBoy84** [comment]
The jailbreak community is not expecting a jailbreak for ios 14.4.x anytime soon, let alone ios 14.5.x

**Comment by joeyoropesa-dev** [comment]
![image](https://user-images.githubusercontent.com/45666011/119553158-a9209f00-bd9b-11eb-8399-9aabf59496c5.png)![image](https://user-images.githubusercontent.com/45666011/119553177-ade55300-bd9b-11eb-9792-b4e17df64b41.png)
